# A config file is required for copyparty to load

[global]
  p: 3923  # Port
  e2dsa  # File indexing and filesystem scanning
  e2ts   # Multimedia indexing
  z, qr  # Zeroconf and qrcode

[accounts]
  admin: admin
  youruser: qhmwjpQw38wRt

[/]
  /w         # The container filesystem place of the default share
  accs:
    A: admin     # The user admin gets all rights
    r: youruser  # available permissions: [r]ead [w]rite [m]ove [d]elete [.]dot files [g]et files without seeing [a]dmin [A]ll

# [/music]
#   /w/music
#   accs:
#     r: *

